Repository Gaia3D/mago3d-client, pull requests merged in 2024-08, with the labels that each got.

#22 관리자 페이지 다국어 처리
  front/packages/admin/src/components/dataset/process/Process.tsx
  front/packages/admin/src/components/dataset/process/ProcessTerrain.tsx
  front/packages/admin/src/components/dataset/process/ProcessTiff.tsx
  front/packages/admin/src/generated/gql/dataset/graphql.ts
  front/packages/admin/src/generated/gql/layerset/graphql.ts
  front/packages/admin/src/locales/en/translation.json
  front/packages/admin/src/locales/ko/translation.json
Labels: enhancement

#25 Front publishing 4
  front/packages/user/index.html
  front/packages/user/src/Main.tsx
  front/packages/user/src/assets/font/Montserrat-Black.woff2
  front/packages/user/src/assets/font/Montserrat-BlackItalic.woff
  front/packages/user/src/assets/font/Montserrat-Bold.woff
  front/packages/user/src/assets/font/Montserrat-Bold.woff2
  front/packages/user/src/assets/font/Montserrat-ExtraBold.woff
  front/packages/user/src/assets/font/Montserrat-ExtraBold.woff2
  front/packages/user/src/assets/font/Montserrat-ExtraLight.woff
  front/packages/user/src/assets/font/Montserrat-ExtraLight.woff2
  front/packages/user/src/assets/font/Montserrat-Light.woff
  front/packages/user/src/assets/font/Montserrat-Light.woff2
  front/packages/user/src/assets/font/Montserrat-Medium.woff
  front/packages/user/src/assets/font/Montserrat-Medium.woff2
  front/packages/user/src/assets/font/Montserrat-Regular.woff
  front/packages/user/src/assets/font/Montserrat-Regular.woff2
  front/packages/user/src/assets/font/Montserrat-SemiBold.woff
  front/packages/user/src/assets/font/Montserrat-SemiBold.woff2
  front/packages/user/src/assets/font/Montserrat-Thin.woff
  front/packages/user/src/assets/font/Montserrat-Thin.woff2
  front/packages/user/src/assets/font/NanumSquareNeoTTF-aLt.eot
  front/packages/user/src/assets/font/NanumSquareNeoTTF-aLt.woff
  front/packages/user/src/assets/font/NanumSquareNeoTTF-aLt.woff2
  front/packages/user/src/assets/font/NanumSquareNeoTTF-bRg.eot
  front/packages/user/src/assets/font/NanumSquareNeoTTF-bRg.woff
  front/packages/user/src/assets/font/NanumSquareNeoTTF-bRg.woff2
  front/packages/user/src/assets/font/NanumSquareNeoTTF-cBd.eot
  front/packages/user/src/assets/font/NanumSquareNeoTTF-cBd.woff
  front/packages/user/src/assets/font/NanumSquareNeoTTF-cBd.woff2
  front/packages/user/src/assets/font/NanumSquareNeoTTF-dEb.eot
  front/packages/user/src/assets/font/NanumSquareNeoTTF-dEb.woff
  front/packages/user/src/assets/font/NanumSquareNeoTTF-dEb.woff2
  front/packages/user/src/assets/font/NanumSquareNeoTTF-eHv.eot
  front/packages/user/src/assets/font/NanumSquareNeoTTF-eHv.woff
  front/packages/user/src/assets/font/NanumSquareNeoTTF-eHv.woff2
  front/packages/user/src/assets/images/compass-direction.png
  front/packages/user/src/assets/images/compass-direction.svg
  front/packages/user/src/assets/images/compass.svg
  front/packages/user/src/assets/images/dark-icon.svg
  front/packages/user/src/assets/images/map.png
  front/packages/user/src/assets/images/map2.png
  front/packages/user/src/assets/scss/setting/_basic.scss
  front/packages/user/src/assets/scss/setting/_etc.scss
  front/packages/user/src/assets/scss/setting/_font.scss
  front/packages/user/src/assets/scss/setting/_setup.scss
  front/packages/user/src/assets/scss/style.scss
  front/packages/user/src/components/AsideMenu.tsx
  front/packages/user/src/components/LanguageSelector.tsx
  front/packages/user/src/components/Map.tsx
  front/packages/user/src/components/MapToolbox.tsx
  front/packages/user/src/components/ObjectToolbox.tsx
  front/packages/user/src/components/SignInfo.tsx
  front/packages/user/src/hooks/useMapTool.tsx
  front/packages/user/src/locales/en/translation.json
  front/packages/user/src/locales/ko/translation.json
  front/packages/user/src/pages/Index.tsx
  front/packages/user/src/recoils/MainMenuState.tsx
Labels: documentation, enhancement

#26 툴바 기능 개발 완료
  front/packages/user/src/api/camera/magoViewCenter.ts
  front/packages/user/src/api/camera/magoViewPoint.ts
  front/packages/user/src/assets/scss/setting/_etc.scss
  front/packages/user/src/components/MapToolbox.tsx
  front/packages/user/src/components/utils/loadGeojson.ts
  front/packages/user/src/hooks/useMapTool.tsx
  front/packages/user/src/pages/Index.tsx
Labels: enhancement

#27 헤더 영역 개발 완료
  front/packages/user/src/assets/scss/setting/_etc.scss
  front/packages/user/src/components/MapToolbox.tsx
  front/packages/user/src/components/SignInfo.tsx
  front/packages/user/src/components/maptool/ClockTool.tsx
  front/packages/user/src/components/maptool/Compass.tsx
  front/packages/user/src/components/maptool/SettingTool.tsx
  front/packages/user/src/hooks/useMapTool.tsx
Labels: enhancement

#29 Assets 검색 목록 조회 기능 구현
  front/packages/shared/src/types/dataset-gen-type.ts
  front/packages/shared/src/types/dataset/doc/mutation.graphql
  front/packages/shared/src/types/dataset/doc/query.graphql
  front/packages/shared/src/types/dataset/gql/gql.ts
  front/packages/shared/src/types/dataset/gql/graphql.ts
  front/packages/shared/src/types/layerset/gql/graphql.ts
  front/packages/user/.env
  front/packages/user/package.json
  front/packages/user/src/App.tsx
  front/packages/user/src/api/ApolloClients.ts
  front/packages/user/src/assets/scss/setting/_basic.scss
  front/packages/user/src/assets/scss/setting/_etc.scss
  front/packages/user/src/components/AsideAssets.tsx
  front/packages/user/src/components/AsideLayer.tsx
  front/packages/user/src/components/AsideMenu.tsx
  front/packages/user/src/components/AsidePanel.tsx
  front/packages/user/src/components/AsideProps.tsx
  front/packages/user/src/components/AssetRow.tsx
  front/packages/user/src/components/SearchInput.tsx
  front/packages/user/src/components/SideCloseButton.tsx
  front/packages/user/src/hooks/useDebounce.ts
  front/packages/user/src/hooks/useInfiniteScroll.ts
  front/packages/user/src/recoils/Data.ts
  front/packages/user/src/recoils/MainMenuState.tsx
  front/packages/user/src/types/assets/Data.ts
  front/pnpm-lock.yaml
Labels: enhancement

#30 Feature new asset 10
  front/packages/shared/codegen.ts
  front/packages/shared/src/types/dataset/doc/query.graphql
  front/packages/shared/src/types/dataset/gql/gql.ts
  front/packages/shared/src/types/dataset/gql/graphql.ts
  front/packages/shared/src/types/layerset/Mutation.ts
  front/packages/shared/src/types/layerset/gql/gql.ts
  front/packages/shared/src/types/layerset/gql/graphql.ts
  front/packages/shared/src/types/layerset/mutation.graphql
  front/packages/shared/src/types/layerset/query.graphql
  front/packages/user/.env
  front/packages/user/src/api/ApolloClients.ts
  front/packages/user/src/api/http.ts
  front/packages/user/src/assets/images/background-map.png
  front/packages/user/src/assets/images/dark-icon.svg
  front/packages/user/src/assets/images/dark-sub-icon.svg
  front/packages/user/src/assets/images/icon-sub.svg
  front/packages/user/src/assets/images/light-compass.svg
  front/packages/user/src/assets/images/light-icon.svg
  front/packages/user/src/assets/images/light-sub-icon.svg
  front/packages/user/src/assets/scss/setting/_basic.scss
  front/packages/user/src/assets/scss/setting/_etc.scss
  front/packages/user/src/assets/scss/setting/_font.scss
  front/packages/user/src/assets/scss/setting/_setup.scss
  front/packages/user/src/components/AsideLayer.tsx
  front/packages/user/src/components/AssetRow.tsx
  front/packages/user/src/components/aside/AsideMenu.tsx
  front/packages/user/src/components/aside/AsidePanel.tsx
  front/packages/user/src/components/aside/asset/AsideAssets.tsx
  front/packages/user/src/components/aside/asset/AssetLoadSpinner.tsx
  front/packages/user/src/components/aside/asset/AssetRow.tsx
  front/packages/user/src/components/aside/layer/AsideLayer.tsx
  front/packages/user/src/components/aside/layer/GroupNode.tsx
  front/packages/user/src/components/aside/layer/LayerNode.tsx
  front/packages/user/src/components/aside/layer/TreeNode.tsx
  front/packages/user/src/components/aside/prop/AsideProps.tsx
  front/packages/user/src/components/maptool/PrintPortal.tsx
  front/packages/user/src/components/modal/FileItem.tsx
  front/packages/user/src/components/modal/FileUpload.tsx
  front/packages/user/src/components/modal/FormatList.tsx
  front/packages/user/src/components/modal/InputWithLabel.tsx
  front/packages/user/src/components/modal/NewAssetModal.tsx
  front/packages/user/src/components/modal/RadioGroup.tsx
  front/packages/user/src/components/modal/ToggleSetting.tsx
  front/packages/user/src/components/modal/newAsset/ConversionGuard.tsx
  front/packages/user/src/components/modal/newAsset/RasterContent.tsx
  front/packages/user/src/components/modal/newAsset/TerrainContent.tsx
  front/packages/user/src/components/modal/newAsset/Tile3DContent.tsx
  front/packages/user/src/components/modal/newAsset/VectorContent.tsx
  front/packages/user/src/components/modal/newAsset/WeatherContent.tsx
  front/packages/user/src/components/providers/GlobeControllerProvider.tsx
  front/packages/user/src/components/utils/optionsData.ts
  front/packages/user/src/pages/Index.tsx
  front/packages/user/src/recoils/Assets.ts
  front/packages/user/src/recoils/Data.ts
  front/packages/user/src/recoils/MainMenuState.tsx
  front/packages/user/src/recoils/Modal.ts
  front/packages/user/src/recoils/Spinner.ts
  front/packages/user/src/types/Common.ts
Labels: documentation, enhancement, wontfix
